export enum ENotificationType {
    BOOKING_CONFIRMATION,
    BOOKING_CANCELLATION,
    BOOKING_PENDING,
    BOOKING_REQUEST,
    CHECK_IN,
    CHECK_OUT,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    DISCOUNT
}